backend/config/routes.rb
Rails.application.routes.draw do
   get 'project/list'
   get 'project/new'
   post 'project/create'
   patch 'project/update'
   get 'project/show'
   get 'project/edit'
   get 'project/delete'

   get 'photo/list'
   get 'photo/new'
   post 'photo/create'
   patch 'photo/update'
   get 'photo/show'
   get 'photo/edit'
   get 'photo/delete'
   
   
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end

backend/app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :project, required: true
    validates_presence_of :description
    has_one_attached :file
 end

backend/app/models/project.rb
class Project < ApplicationRecord
    has_many :photos
    validates_presence_of :title
    validates_presence_of :description
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

backend/app/controllers/photo_controller.rb
class PhotoController < ApplicationController
    def list
        @photos = Photo.all 
    end

    def show
        @photo = Photo.find(params[:id])
    end

    def new
        @photo = Photo.new
        @project_id = params[:project_id]
    end

    def create
        @photo = Photo.new(photo_params)
        
        puts @photo.project_id
        puts @photo.description
        @photo.validate!
        puts @photo.errors.full_messages

        if @photo.save 
            redirect_to :action => 'show', :controller => 'project', :id => @photo.project_id
        else
            
            render :action => 'new'
        end
    end

    def edit
        @photo = Photo.find(params[:id])
    end

    def update
        @photo = Photo.find(params[:id])

        if @photo.update_attributes(photo_params)
            redirect_to :action => 'show', :id => @photo
        else
            render :action => 'edit'
        end
    end

    def photo_params
        params.require(:photo).permit(:project_id, :description, :file)
    end
    
    def delete
        photo = Photo.find(params[:id])
        project_id = photo.project_id
        photo.destroy()
        redirect_to :action => 'show', :controller => 'project', :id => project_id
    end
end

backend/app/controllers/project_controller.rb
class ProjectController < ApplicationController
    def list
        @projects = Project.all 
    end

    def show
        @project = Project.find(params[:id])
        @photos = Photo.where(project_id: params[:id])
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        if @project.save 
            redirect_to :action => 'list'
        else
            render :action => 'new'
        end
    end

    def project_params
        params.require(:projects).permit(:title, :description)
    end

    def edit
        @project = Project.find(params[:id])
    end

    def update
        @project = Project.find(params[:id])

        if @project.update_attributes(project_param)
            redirect_to :action => 'show', :id => @project
        else
            render :action => 'edit'
        end
    end

    def project_param 
        params.require(:project).permit(:title, :description)
    end

    def delete
        Project.find(params[:id]).destroy
        redirect_to :action => 'list'
    end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/photos_helper.rb
module PhotosHelper
end

backend/app/helpers/project_helper.rb
module ProjectHelper
end

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/photo/edit.html.erb
<h1>Edit Photo</h1>

<%= form_for @photo, :url =>{:action => "update", :id =>@photo} do |f| %>

<p>Project ID: <%= f.text_field 'project_id' %></p>
<p>Description<br/>

<%= f.text_area 'description' %></p>
<%= f.file_field 'file'%>
<%= f.submit "Save changes" %>
<% end %>

<%= link_to 'Back', {:action => 'show', :controller => 'project', :id => @photo.project_id} %>

backend/app/views/photo/list.html.erb
<% if @photos.blank? %>
<p>There are not any photos currently in the system.</p>
<% else %>
<p>These are the current photos in our system</p>

<ul id = "photos">
   <% @photos.each do |c| %>
    <li>
    <%= link_to c.id, {:action => "show", :id => c.id} -%>
    <b> <%= link_to 'Edit', {:action => "edit",:id => c.id} %></b>
    <b> <%= link_to "Delete", {:action => 'delete', :id => c.id},
      :confirm => "Are you sure you want to delete this item?" %></b> <br>
    <% if c.file.attached? %>
      <%= image_tag(url_for(c.file), size: "200x100") %>
    <% end %>
    
 </li>
   <% end %>
</ul>

<% end %>
<p><%= link_to "Add new Photo", {:action => 'new' }%></p>

backend/app/views/photo/new.html.erb
<h1>Add new photo</h1>

<%= form_for(Photo.new, url: photo_create_url, :html => { :multipart => true }) do |f| %>
<p><label for = "photo_project_id">ProjectID</label>:

<%= f.text_field :project_id, value: @project_id%></p>
<p><label for = "photo_description">Description</label>:

<%= f.text_area :description %></p>

<%= f.file_field :file %>

<%= submit_tag "Create" %>
<% end -%>
<%= link_to 'Back', {:action => 'show', :controller => 'project', :id => @project_id} %>

backend/app/views/photo/show.html.erb
<p>
   <strong>Project: </strong> <%= @photo.project_id %><br />
   <strong>Description: </strong> <%= @photo.description %><br />
   <% if @photo.file.attached? %>
      <%= image_tag(url_for(@photo.file), size: "200x100") %> 
    <% end %>
</p>

<hr />

<%= link_to 'Back', {:action => 'list'} %>

backend/app/views/project/edit.html.erb
<h1>Edit Project Detail</h1>

<%= form_for @project, :url =>{:action => "update", :id =>@project} do |f| %>

<p>Title: <%= f.text_field 'title' %></p>
<p>Description<br/>

<%= f.text_area 'description' %></p>
<%= f.submit "Save changes" %>
<% end %>

<%= link_to 'Back', {:action => 'list' } %>

backend/app/views/project/list.html.erb
<% if @projects.blank? %>
<p>There are not any projects currently in the system.</p>
<% else %>
<p>These are the current projects in our system</p>

<ul id = "projects">
   <% @projects.each do |c| %>
    <li>
    <%= link_to c.title, {:action => "show", :id => c.id} -%>
    <b> <%= link_to 'Edit', {:action => "edit",:id => c.id} %></b>
    <b> <%= link_to "Delete", {:action => 'delete', :id => c.id},
      :confirm => "Are you sure you want to delete this item?" %></b>
    
 </li>
   <% end %>
</ul>

<% end %>
<p><%= link_to "Add new Project", {:action => 'new' }%></p>

backend/app/views/project/new.html.erb
<h1>Add new project</h1>

<%= form_tag :action => 'create' do %>
<p><label for = "project_title">Title</label>:

<%= text_field 'projects', 'title' %></p>
<p><label for = "project_description">Description</label>:

<%= text_area 'projects', 'description' %></p>
<%= submit_tag "Create" %>
<% end -%>
<%= link_to 'Back', {:action => 'list'} %>

backend/app/views/project/show.html.erb
<h1><%= @project.title %></h1>

<p>
   <strong>ID: </strong> <%= @project.id %><br />
   <strong>Description: </strong> <%= @project.description %><br />
</p>
<% @photos.each do |c| %>
   <%= image_tag(url_for(c.file), size: "200x100") %> 
   <%= c.description%>
   <br />
   <%= link_to 'Edit', {:action => "edit", :controller =>"photo", :id => c.id} %>
   <%= link_to 'Delete', {:action => "delete", :controller =>"photo", :id => c.id} %>
   <br />
<% end %>
<br />
<b> <%= link_to 'Add Photo', {:action => "new", :controller =>"photo", :project_id => @project.id} %></b>

<hr />

<%= link_to 'Back', {:action => 'list'} %>